### ISSUE TITLE
ApplyOfflineConversions uploaded data can't see into my account under "Offline conversion"

### ISSUE THREAD

**Issue by NikhilThombare-Cuelogic** [BingAds/BingAds-Python-SDK#174] opened 2021-02-03 07:46 UTC
Using this method I am uploading offline conversion with all necessary information. It is running without any error but I can't see uploaded conversion into my account. Please help me with that. On the "Offline conversion" menu I can see only the upload button only but I can't see data uploaded by SDK. 

```
 output_status_message("-----\nApplyOfflineConversions:")
 apply_offline_conversions_response = campaign_service.ApplyOfflineConversions(
 OfflineConversions=offline_conversions)

 output_status_message("PartialErrors:")
 output_array_of_batcherror(apply_offline_conversions_response)
```

**Comment by qitia** [comment] 2021-02-22 09:28
could you please provide some more detail thus we can debug? like tracking id for instance. you can also touch support team for help and provide them with customerid/accountid.

**Comment by qitia** [comment] 2021-02-23 06:11
Talked to guys on this feature and the Offline conversion history is for UI uploaded offline conversion only. those via API uploaded will not be shown in the offline conversion history page.

go to conversion goal page, and check 'all conv.' to see if the API call succeed finally or not.

I will close this as by design as of now and feel free to reopen it @NikhilThombare-Cuelogic

**Closed by qitia** 2021-02-23 06:11 UTC

**Comment by NikhilThombare-Cuelogic** [comment] 2021-02-23 06:20
> Talked to guys on this feature and the Offline conversion history is for UI uploaded offline conversion only. those via API uploaded will not be shown in the offline conversion history page.
> 
> go to conversion goal page, and check 'all conv.' to see if the API call succeed finally or not.
> 
> I will close this as by design as of now and feel free to reopen it @NikhilThombare-Cuelogic

Sure @qitia. I can see offline conversions uploaded count get increased Now It is working fine for me. Thanks for the help.

**Comment by lcironfocus** [comment] 2025-03-05 19:12
> offline conversions uploaded

Hi @NikhilThombare-Cuelogic, I'm also experiencing the same issue as you. When you mentioned that you can see the 'offline conversion uploaded count' increase, where exactly can I find that in the UI? Is it the value of 'All conv.'?

![Image](https://github.com/user-attachments/assets/2218f629-2b1d-4f07-a62c-1d3156e61c14)
